name: "Build & Release"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build-android:
    name: Build and Release APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'
      
      - name: Get Flutter Dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: build/app/outputs/apk/release/*.apk

  build-ios:
    name: Build and Release iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'
      
      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign
      
      - run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: ios-ipa
          path: build/ios/iphoneos/*.ipa

  create-release:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Android APK Artifact
        uses: actions/download-artifact@v2
        with:
          name: android-apk
          path: ./artifacts/android

      - name: Download iOS IPA Artifact
        uses: actions/download-artifact@v2
        with:
          name: ios-ipa
          path: ./artifacts/ios

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v1.0.${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release of the Android and iOS apps.
          draft: false
          prerelease: false

      - name: Upload Android APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/android/*.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload iOS IPA to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/ios/*.ipa
          asset_name: app-release.ipa
          asset_content_type: application/octet-stream
