on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build-android:
    name: Build and Release APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - name: Get Flutter Dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: build/app/outputs/apk/release/*.apk

  build-ios:
    name: Build and Release iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./artifacts/android/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}